# Generated by Django 3.2.23 on 2024-02-01 13:12

import django.core.validators
from django.db import migrations, models
import forms_advanced.web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.PositiveSmallIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='last_name',
            field=models.CharField(default='asdad', max_length=32, validators=[forms_advanced.web.models.validate_first_name, django.core.validators.MinLengthValidator(2)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=32, validators=[forms_advanced.web.models.validate_first_name, django.core.validators.MinLengthValidator(2)]),
        ),
    ]
